using System.ComponentModel.DataAnnotations;
using Dragon.Common.Contracts.Enums;

namespace Dragon.Common.Contracts.Integration.Classes
{
    /// <summary>
    /// Start Game / Login Integration Request.
    /// </summary>
    public class StartGameRequest : BaseIntegrationRequest
    {
        /// <summary>
        /// Token passed to the launcher during the launch. Generated by operator, validated by the operator.
        /// </summary>
        /// <value></value>
        [Required]
        public string Token { get; set; }
        /// <summary>
        /// Context passed to the launcher.
        /// </summary>
        /// <value></value>
        public string Context { get; set; }
        /// <summary>
        /// IP of the player.
        /// </summary>
        /// <value></value>
        public string IP { get; set; }
        /// <summary>
        /// Language passed to the launcher.
        /// </summary>
        /// <value></value>
        public string Language { get; set; }
        /// <summary>
        /// Game Id of the game launched
        /// </summary>
        /// <value></value>
        [Required]
        public string GameId { get; set; }
        /// <summary>
        /// Channel game was launch on.
        /// Different channels.
        /// Desktop  0 
        /// Mobile   1
        /// Terminal 2
        /// Mini     3
        /// </summary>
        /// <value></value>
        [Required]
        public Channel Channel { get; set; }

        /// <summary>
        /// StartGameRequest const.
        /// </summary>
        public StartGameRequest()
        {

        }
    }
}